# Netlify configuration file

[build]
# The root of the project
base = "."

# Command to install Python dependencies AND download the spaCy model
command = "pip install -r requirements.txt && python -m spacy download en_core_web_sm"

# Directory where the serverless functions are located
functions = "netlify/functions"

# Directory containing the static UI files to be published
publish = "public"

[build.environment]
# Force the Python version for the build environment to ensure compatibility
PYTHON_VERSION = "3.9"

[[redirects]]
# Redirect all traffic to our serverless function handler
from = "/*"
to = "/.netlify/functions/api"
status = 200
